### ISSUE TITLE
Argument 1 passed to Author::setTitle() must be an instance of PersonTitle

### ISSUE THREAD

**Issue by memduhcagridemir** [academic/VipaImportBundle#31]
Importing from OJS2.4.8 gives the following error.

> Catchable Fatal Error: Argument 1 passed to Ojs\JournalBundle\Entity\Author::setTitle() must be an instance of Ojs\JournalBundle\Entity\PersonTitle, string given, called in path_to_ojs/vendor/ojs/import-bundle/Importer/PKP/ArticleImporter.php on line 269

I checked Author class, its setter defined as:

> ```
> /**
>  * @param  PersonTitle $title
>  * @return $this
>  */
> public function setTitle(PersonTitle $title = null)
> ```

And the call throwing the error is:

> $author->setTitle('-');

I changed the call with

> $author->setTitle(null);

It works ok for now. I will comment to this issue if I encounter any problems related to change. :relaxed:

**Comment by utkuaydin** [comment]
That changed yesterday, with ojs/ojs@2ca9f26. I'll take care of it. Thanks.
